---
default: true

# MD013/line-length - Line length
MD013:
  # Number of characters
  line_length: 100
   # Number of characters for headings
  heading_line_length: 80
  # Number of characters for code blocks
  code_block_line_length: 100
  # Include tables
  tables: false

# MD034/no-bare-urls - Bare URL used
MD034: false
