# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2.2"

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = "bfee-debian-testing-bare"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
  end

  config.vm.provision "ansible", run: "always" do |ansible|
    ansible.playbook = "../../ping.yml"
#    ansible.verbose = "vvvv"
  end
  if ARGV.include? '--provision-with'
    config.vm.provision "ping", type: "ansible", run: "always" do |ansible|
      ansible.playbook = "../../ping.yml"
    end
    config.vm.provision "facts", type: "ansible", run: "always" do |ansible|
      ansible.playbook = "../../facts.yml"
    end
  end
end
