# -*- mode: ruby -*-
# vim: set ft=ruby :
# frozen_string_literal: true

Vagrant.require_version '>= 2.2'

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure('2') do |config| # rubocop:disable Metrics/BlockLength
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = 'bfee-vagrantVbox-ubuntu-lts-bare'

  config.vm.synced_folder '.', '/vagrant'

  config.vm.provider 'virtualbox' do |vb|
    vb.name = 'packer-ubuntu-lts-bare'
    vb.gui = false
  end

  config.vm.provision 'ansible', run: 'always' do |ansible|
    ansible.playbook = '../../../ansible-homelab/playbooks/ping.yml'
    ansible.compatibility_mode = '2.0'
    #    ansible.verbose = "vvvv"
  end
  if ARGV.include? '--provision-with'
    config.vm.provision 'ping', type: 'ansible', run: 'always' do |ansible|
      ansible.playbook = '../../../ansible-homelab/playbooks/ping.yml'
      ansible.compatibility_mode = '2.0'
    end
    config.vm.provision 'facts', type: 'ansible', run: 'always' do |ansible|
      ansible.playbook = '../../../ansible-homelab/playbooks/facts.yml'
      ansible.compatibility_mode = '2.0'
      ansible.host_vars = {
        'default' => {
          'test_key' => 'some value'
        }
      }
    end
    config.vm.provision 'test', type: 'ansible', run: 'always' do |ansible|
      ansible.playbook = '../../../ansible-homelab/playbooks/test.yml'
      ansible.compatibility_mode = '2.0'
    end
    config.vm.provision 'server', type: 'ansible', run: 'always' do |ansible|
      ansible.playbook = '../../../ansible-homelab/main.yml'
      ansible.compatibility_mode = '2.0'
      ansible.groups = {
        'servers' => ['default']
      }
    end
    config.vm.provision 'desktop', type: 'ansible', run: 'always' do |ansible|
      ansible.playbook = '../../../ansible-homelab/main.yml'
      ansible.compatibility_mode = '2.0'
      ansible.groups = {
        'desktops' => ['default']
      }
    end
  end
end
